apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: mynamespace
data:
  default.conf: |
    server {
      listen 80;

      location / {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
      }
    }
