apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-php-demo
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynatrace-php-demo
  template:
    metadata:
      labels:
        app: dynatrace-php-demo
    spec:
      volumes:
        - name: app-code
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf

      containers:
        - name: php-fpm
          image: ghcr.io/gianfrancococchieri-commits/dynatrace-php-demo:latest
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
