events {}

http {
  server {
    listen 80;

    # ALLINEA QUI il path reale dove NGINX vede il codice
    root /app;
    index index.php;

    location / {
      try_files $uri /index.php =404;
    }

    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
    }
  }
}
